### ISSUE TITLE
No GPS Fix when Time Sync enabled

### ISSUE THREAD

**Issue by McQuack13** [mikaelnousiainen/RS41ng#13]
Hi! Whenever I enable GPS Time Sync for any transmission, the packets indefinitely come with latitude, longitude, and altitude equal to 0. The same config, same radiosonde, but without time sync enabled, returns proper coordinates. The value of the sync is irrelevant, happens on any value, such as 10s, 15s, etc. Why is this happening? Is there an easy and quick fix for this? Thanks in advance!

**Comment by mikaelnousiainen** [comment]
Thanks for the report, I will need to test this.

**Comment by DL4OCE** [comment]
Don't know whether this is related to the '/usr/bin/ld: template.c:(.text+0x81): undefined reference to `strlcpy'' issue or the setting mentioned above, but I NEVER got anything else than 0 values in the GPS position:
08:22:48$ fm DL4OCE-4 to APZ41N-0 via WIDE1-1,WIDE2-1 UI  PID=F0
          !0000.00S/00000.00Wb000/000/A=000000/P32S0T36V0186C00 JJ00AA00AA00 - RS41ng

This happens ALTHOUGH I've set all the GPS sync stuff to no:
#define APRS_TIME_SYNC_SECONDS 0
#define APRS_TIME_SYNC_OFFSET_SECONDS 0
#define HORUS_V1_TIME_SYNC_SECONDS 0
...

**Comment by mikaelnousiainen** [comment]
Please pull the latest code and test again. We have recent reports of time sync usage where GPS works.
