### ISSUE TITLE
BMP 280

### ISSUE THREAD

**Issue by aledorrego** [mikaelnousiainen/RS41ng#4]
Would you be so kind as to upload a .hex file so that I can test if my board works?  the probe starts at 38 seconds and begins transmissions.  but i am not getting the readings from the bmp280 sensor.  he told me that pull up resistors are going.  the bmp280 board has built-in 10k ones.  but I can't get the data. I can't find the connection diagram of the RS41 with the BMP280. I assumed that it goes SDA / SDA, SCL / SCL, GND and + V (I don't know which pin of the probe)

**Comment by mikaelnousiainen** [comment]
@aledorrego The README file indicates the following pinout:

```
______________________|           |______________________
|                                                       |
|   1           2           3           4           5   |
|                                                       |
|   6           7           8           9          10   |
|_______________________________________________________|
```

(View from the bottom of the sonde, pay attention to the gap in the connector)

Connect your I²C device (e.g. BMP280) to the following pins:

3 - MCU switched 3.3V out to external device
4 - I2C2_SCL -- This is the external I²C port clock pin for Si5351 and sensors
5 - GND
10 - I2C2_SDA -- This is the external I²C port data pin for Si5351 and sensors

**Comment by mikaelnousiainen** [comment]
@aledorrego Also, the BMP280 readings are only available if you specifically add them to one of the following: APRS comment text, CW text or FSQ message. Horus V2 includes them in custom data. Other modes do not have this info directly.

See the config.c file for defining the text messages for each mode.
