### ISSUE TITLE
how to make a pull request

### ISSUE THREAD

**Issue by whallmann** [mikaelnousiainen/RS41ng#64]
Hi Mikael, have some new code for you about this rotating HORUS_V2 2nd Frequency. I did  a local commit. but i wonder how to make a pull request to this project? Do you have to add my user anywhere? I never made a pull-request before sorry.

got some errors not know how to interpret this

 wolfgang@Wolf-Deb-Laptop:~/RS41ng$ git push
Username for 'https://github.com': whallmann
Password for 'https://whallmann@github.com': 
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/mikaelnousiainen/RS41ng.git/'

**Comment by whallmann** [comment]
now read further and tried a Personal Access Token
but not succeeded sorry.
wolfgang@Wolf-Deb-Laptop:~/RS41ng$ git push
Username for 'https://github.com': ghp_...........................................
Password for 'https://ghp_......................@github.com': 
remote: Permission to mikaelnousiainen/RS41ng.git denied to whallmann.
fatal: unable to access 'https://github.com/mikaelnousiainen/RS41ng.git/': The requested URL returned error: 403
wolfgang@Wolf-Deb-Laptop:~/RS41ng$ 
Any hints? Should i send you the files by email?

**Comment by mikaelnousiainen** [comment]
@whallmann Please have a look at GitHub documentation for pull requests. You need to fork my RS41ng repository first, make your changes in your local fork and commit them. After that, you can create a PR in the GitHub UI using a *web browser*.

There is some documentation here: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

Closing as this is not an issue in RS41ng.
