### ISSUE TITLE
ax25.c compile error

### ISSUE THREAD

**Issue by buttim** [mikaelnousiainen/RS41ng#82]
The last modification to the file src/codecs/ax25.c is broken.
Line 92 has a missing open parentheses (and a useless final semicolon):

`header->destination_ssid = (uint8_t) destination_ssid >= 'A' ? destination_ssid - 7 : destination_ssid);;`

and should be (probably) corrected to:

`header->destination_ssid = (uint8_t)(destination_ssid >= 'A' ? destination_ssid - 7 : destination_ssid);`

**Comment by mikaelnousiainen** [comment]
@buttim Thanks for reporting this, should be fixed now!
